import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:stoxplay/features/profile_page/presentation/pages/profile_page.dart';
import 'package:stoxplay/utils/common/widgets/glow_icon.dart';
import 'package:stoxplay/utils/constants/app_assets.dart';
import 'package:stoxplay/utils/constants/app_colors.dart';
import 'package:stoxplay/utils/models/contest_model.dart';

List<BottomNavigationBarItem> navBarList = [
  BottomNavigationBarItem(
    icon: Image.asset(AppAssets.monitorIcon, height: 24.h, width: 24.w, color: AppColors.black),
    activeIcon: GlowIcon(
      glowColor: AppColors.primaryPurple,
      child: Image.asset(AppAssets.monitorIcon, height: 24.h, width: 24.w, color: AppColors.primaryPurple),
    ),
    label: '',
  ),
  BottomNavigationBarItem(
    icon: Image.asset(AppAssets.monitorIcon, height: 24.h, width: 24.w),
    activeIcon: GlowIcon(
      glowColor: AppColors.primaryPurple,
      child: Image.asset(AppAssets.monitorIcon, height: 24.h, width: 24.w, color: AppColors.primaryPurple),
    ),
    label: '',
  ),
  BottomNavigationBarItem(
    icon: Image.asset(AppAssets.insightIcon, height: 24.h, width: 24.w),
    activeIcon: GlowIcon(
      glowColor: AppColors.primaryPurple,
      child: Image.asset(AppAssets.insightIcon, height: 24.h, width: 24.w, color: AppColors.primaryPurple),
    ),
    label: '',
  ),
  BottomNavigationBarItem(
    icon: Image.asset(AppAssets.profileIcon, height: 24, width: 24),
    activeIcon: GlowIcon(
      glowColor: AppColors.primaryPurple,
      child: Image.asset(AppAssets.profileIcon, height: 24.h, width: 24.w, color: AppColors.primaryPurple),
    ),
    label: '',
  ),
];

final List<ContestStaticModel> contests = [
  ContestStaticModel(
    title: "Bank Wars",
    price: "10,50,000/-",
    timeLeft: "(09:10:59)",
    image: "assets/images/bank_wars.png",
    contestPriceList: [
      ContestPrice(contestPrice: 500, spots: '2000', prizePool: "8,10,000"),
      ContestPrice(contestPrice: 1000, spots: '1000', prizePool: "8,10,000"),
      ContestPrice(contestPrice: 5000, spots: '500', prizePool: "20,40,000"),
    ],
    stocks: [
      Stock(
        stockName: "HDFC Bank Ltd.",
        id: "1",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/hdfc_bank.png",
      ),
      Stock(
        stockName: "ICICI Bank Ltd.",
        id: "2",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/icici_bank.png",
      ),
      Stock(
        stockName: "SBI.",
        id: "3",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/sbi_bank.png",
      ),
      Stock(
        stockName: "Kotak Mahindra Bank Ltd.",
        id: "4",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/kotak_bank.png",
      ),
      Stock(
        stockName: "Axis Bank",
        id: "5",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/axis_bank.png",
      ),
      Stock(
        stockName: "Bank Of Baroda",
        id: "6",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/bank_of_baroda.png",
      ),
      Stock(
        stockName: "PNB Bank Ltd.",
        id: "7",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/pnb_bank.png",
      ),
      Stock(
        stockName: "IDBI Bank Ltd.",
        id: "8",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/idbi_bank.png",
      ),
      Stock(
        stockName: "Canara Bank",
        id: "9",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/canara_bank.png",
      ),
      Stock(
        stockName: "IDFC Bank",
        id: "10",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/idfc_bank.png",
      ),
      Stock(
        stockName: "Indusind Bank Ltd.",
        id: "11",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/indusind_bank.png",
      ),
      Stock(
        stockName: "Union Bank Ltd.",
        id: "12",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/union_bank.png",
      ),
      Stock(
        stockName: "Indian bank",
        id: "13",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/indian_bank.png",
      ),
      Stock(
        stockName: "Central Bank Ltd.",
        id: "14",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/central_bank.png",
      ),
      Stock(
        stockName: "Bank of India",
        id: "15",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/boi_bank.png",
      ),
      Stock(
        stockName: "Karnataka Bank",
        id: "16",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/karnataka_bank.png",
      ),
      Stock(
        stockName: "Federal Bank",
        id: "17",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/federal_bank.png",
      ),
      Stock(
        stockName: "AU small finance bank",
        id: "18",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/au_small_fin_bank.png",
      ),
      Stock(
        stockName: "Bank of Maharashtra",
        id: "19",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/bank_of_maharashtra.png",
      ),
      Stock(
        stockName: "Bandhan Bank",
        id: "20",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/bandhan_bank.png",
      ),
      Stock(
        stockName: "RBL Bank",
        id: "21",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/rbl_bank.png",
      ),
      Stock(
        stockName: "Yes Bank",
        id: "22",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/yes_bank.png",
      ),
    ],
  ),
  ContestStaticModel(
    title: "Battle of Energy",
    price: "10,50,000/-",
    timeLeft: "(09:10:59)",
    image: "assets/images/battle_of_energy.png",
    contestPriceList: [
      ContestPrice(contestPrice: 500, spots: '2000', prizePool: "8,10,000"),
      ContestPrice(contestPrice: 1000, spots: '1000', prizePool: "8,10,000"),
      ContestPrice(contestPrice: 5000, spots: '500', prizePool: "20,40,000"),
    ],
    stocks: [
      Stock(
        stockName: "HDFC Bank Ltd.",
        id: "1",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/hdfc_bank.png",
      ),
      Stock(
        stockName: "ICICI Bank Ltd.",
        id: "2",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/icici_bank.png",
      ),
      Stock(
        stockName: "SBI.",
        id: "3",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/sbi_bank.png",
      ),
      Stock(
        stockName: "Kotak Mahindra Bank Ltd.",
        id: "4",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/kotak_bank.png",
      ),
      Stock(
        stockName: "Axis Bank",
        id: "5",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/axis_bank.png",
      ),
      Stock(
        stockName: "Bank Of Baroda",
        id: "6",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/bank_of_baroda.png",
      ),
      Stock(
        stockName: "PNB Bank Ltd.",
        id: "7",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/pnb_bank.png",
      ),
      Stock(
        stockName: "IDBI Bank Ltd.",
        id: "8",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/idbi_bank.png",
      ),
      Stock(
        stockName: "Canara Bank",
        id: "9",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/canara_bank.png",
      ),
      Stock(
        stockName: "IDFC Bank",
        id: "10",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/idfc_bank.png",
      ),
      Stock(
        stockName: "Indusind Bank Ltd.",
        id: "11",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/indusind_bank.png",
      ),
      Stock(
        stockName: "Union Bank Ltd.",
        id: "12",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/union_bank.png",
      ),
      Stock(
        stockName: "Indian bank",
        id: "13",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/indian_bank.png",
      ),
      Stock(
        stockName: "Central Bank Ltd.",
        id: "14",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/central_bank.png",
      ),
      Stock(
        stockName: "Bank of India",
        id: "15",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/boi_bank.png",
      ),
      Stock(
        stockName: "Karnataka Bank",
        id: "16",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/karnataka_bank.png",
      ),
      Stock(
        stockName: "Federal Bank",
        id: "17",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/federal_bank.png",
      ),
      Stock(
        stockName: "AU small finance bank",
        id: "18",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/au_small_fin_bank.png",
      ),
      Stock(
        stockName: "Bank of Maharashtra",
        id: "19",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/bank_of_maharashtra.png",
      ),
      Stock(
        stockName: "Bandhan Bank",
        id: "20",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/bandhan_bank.png",
      ),
      Stock(
        stockName: "RBL Bank",
        id: "21",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/rbl_bank.png",
      ),
      Stock(
        stockName: "Yes Bank",
        id: "22",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/yes_bank.png",
      ),
    ],
  ),
  ContestStaticModel(
    title: "Tech Clash",
    price: "10,50,000/-",
    timeLeft: "(09:10:59)",
    image: "assets/images/tech_clash.png",
    contestPriceList: [
      ContestPrice(contestPrice: 500, spots: '2000', prizePool: "8,10,000"),
      ContestPrice(contestPrice: 1000, spots: '1000', prizePool: "8,10,000"),
      ContestPrice(contestPrice: 5000, spots: '500', prizePool: "20,40,000"),
    ],
    stocks: [
      Stock(
        stockName: "HDFC Bank Ltd.",
        id: "1",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/hdfc_bank.png",
      ),
      Stock(
        stockName: "ICICI Bank Ltd.",
        id: "2",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/icici_bank.png",
      ),
      Stock(
        stockName: "SBI.",
        id: "3",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/sbi_bank.png",
      ),
      Stock(
        stockName: "Kotak Mahindra Bank Ltd.",
        id: "4",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/kotak_bank.png",
      ),
      Stock(
        stockName: "Axis Bank",
        id: "5",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/axis_bank.png",
      ),
      Stock(
        stockName: "Bank Of Baroda",
        id: "6",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/bank_of_baroda.png",
      ),
      Stock(
        stockName: "PNB Bank Ltd.",
        id: "7",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/pnb_bank.png",
      ),
      Stock(
        stockName: "IDBI Bank Ltd.",
        id: "8",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/idbi_bank.png",
      ),
      Stock(
        stockName: "Canara Bank",
        id: "9",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/canara_bank.png",
      ),
      Stock(
        stockName: "IDFC Bank",
        id: "10",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/idfc_bank.png",
      ),
      Stock(
        stockName: "Indusind Bank Ltd.",
        id: "11",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/indusind_bank.png",
      ),
      Stock(
        stockName: "Union Bank Ltd.",
        id: "12",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/union_bank.png",
      ),
      Stock(
        stockName: "Indian bank",
        id: "13",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/indian_bank.png",
      ),
      Stock(
        stockName: "Central Bank Ltd.",
        id: "14",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/central_bank.png",
      ),
      Stock(
        stockName: "Bank of India",
        id: "15",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/boi_bank.png",
      ),
      Stock(
        stockName: "Karnataka Bank",
        id: "16",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/karnataka_bank.png",
      ),
      Stock(
        stockName: "Federal Bank",
        id: "17",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/federal_bank.png",
      ),
      Stock(
        stockName: "AU small finance bank",
        id: "18",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/au_small_fin_bank.png",
      ),
      Stock(
        stockName: "Bank of Maharashtra",
        id: "19",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/bank_of_maharashtra.png",
      ),
      Stock(
        stockName: "Bandhan Bank",
        id: "20",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/bandhan_bank.png",
      ),
      Stock(
        stockName: "RBL Bank",
        id: "21",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/rbl_bank.png",
      ),
      Stock(
        stockName: "Yes Bank",
        id: "22",
        stockPrice: "1,629.40",
        percentage: "-1.05%",
        image: "assets/images/bank_wars/yes_bank.png",
      ),
    ],
  ),
];

/// FontStyles
final selectStocksStyle = TextStyle(
  fontWeight: FontWeight.bold,
  fontSize: 35.sp,
  color: AppColors.primaryPurple,
  height: 1.0,
  letterSpacing: 0.0,
  shadows: [
    Shadow(
      offset: Offset(0, 4),
      blurRadius: 10,
      color: AppColors.black.withOpacity(0.15), // #00000040 in Flutter ARGB format
    ),
  ],
);

BoxDecoration primaryContainerDecoration = BoxDecoration(
  color: AppColors.white,
  borderRadius: BorderRadius.circular(12.r),
  boxShadow: [
    BoxShadow(color: AppColors.blue7E.withOpacity(0.3), offset: const Offset(0, 0), blurRadius: 12, spreadRadius: 1),
  ],
  border: Border.all(color: AppColors.blue7E.withOpacity(0.5)),
);
BoxDecoration boxDecorationForContestWidget = BoxDecoration(
  color: AppColors.white,
  borderRadius: BorderRadius.circular(12.r),
  boxShadow: [BoxShadow(color: AppColors.black6767.withOpacity(0.2), blurRadius: 12, spreadRadius: 1)],
  border: Border.all(color: AppColors.black6767.withOpacity(0.5)),
);

List<ProfileItemModel> profileItems = [
  ProfileItemModel(icon: AppAssets.playIcon, title: "Playing History"),
  ProfileItemModel(icon: AppAssets.personalInfoIcon, title: "Personal Info"),
  ProfileItemModel(icon: AppAssets.playIcon, title: "How to Play"),
  ProfileItemModel(icon: AppAssets.helpIcon, title: "Contact Us"),
  ProfileItemModel(icon: AppAssets.termsAndConditionsIcon, title: "T&C of Zestox Technologies"),
  ProfileItemModel(icon: AppAssets.userProfileIcon, title: "About StoxPlay"),
  ProfileItemModel(icon: AppAssets.logoutIcon, title: "Logout"),
];

final List<Map<String, dynamic>> leaderboard = [
  {
    'name': 'Rajesh Kumar',
    'avatar': 'https://randomuser.me/api/portraits/men/1.jpg',
    'points': 120,
    'isCrown': true,
    'isCurrentUser': true,
  },
  {
    'name': 'Amit Sharma',
    'avatar': 'https://randomuser.me/api/portraits/women/2.jpg',
    'points': 120,
    'isCrown': false,
    'isCurrentUser': false,
  },
  {
    'name': 'Vikram Singh',
    'avatar': 'https://randomuser.me/api/portraits/men/3.jpg',
    'points': 120,
    'isCrown': true,
    'isCurrentUser': false,
  },
  {
    'name': 'Arjun Patel',
    'avatar': 'https://randomuser.me/api/portraits/men/4.jpg',
    'points': 120,
    'isCrown': false,
    'isCurrentUser': false,
  },
  {
    'name': 'Ravi Mehta',
    'avatar': 'https://randomuser.me/api/portraits/men/5.jpg',
    'points': 120,
    'isCrown': false,
    'isCurrentUser': false,
  },
  {
    'name': 'Oliver Johnson',
    'avatar': 'https://randomuser.me/api/portraits/men/6.jpg',
    'points': 120,
    'isCrown': false,
    'isCurrentUser': false,
  },
  {
    'name': 'Ethan Brown',
    'avatar': 'https://randomuser.me/api/portraits/men/7.jpg',
    'points': 120,
    'isCrown': false,
    'isCurrentUser': false,
  },
  {
    'name': 'Liam Davis',
    'avatar': 'https://randomuser.me/api/portraits/men/8.jpg',
    'points': 120,
    'isCrown': false,
    'isCurrentUser': false,
  },
  {
    'name': 'Noah Wilson',
    'avatar': 'https://randomuser.me/api/portraits/men/9.jpg',
    'points': 120,
    'isCrown': false,
    'isCurrentUser': false,
  },
  {
    'name': 'Lucas Taylor',
    'avatar': 'https://randomuser.me/api/portraits/men/10.jpg',
    'points': 120,
    'isCrown': false,
    'isCurrentUser': false,
  },
];
